// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'constitution',
    'specification',
    'plan',
    'tasks',
    {
      type: 'category',
      label: 'The Embodied Mind',
      items: [
        {
          type: 'autogenerated',
          dirName: 'physical-ai-book',
        },
      ],
    },
    {
      type: 'category',
      label: 'Specifications',
      items: [{type: 'autogenerated', dirName: 'specs'}],
    },
  ],
};

export default sidebars;
